### ISSUE TITLE
plot intervals for era5 and mera datasets on top of our inventory tools

### ISSUE THREAD

**Issue by frolovsa** [noaa-psd/observation-inventory-utils#17]
Using examples in 
https://docs.google.com/presentation/d/1UhjQhSjIx6li2pi78iZsTsVGQ3CfFQ36bbpiZBxJECI/edit#slide=id.g11e2af68b3a_0_61

Add orange (era5) and blue (mera 21c) lines on top of our inventory plots. The location of the lines will be below the zero line on y-axis

The duration of the lines will be hard coded into the yaml files.

**Comment by frolovsa** [comment]
provide steve with a sample input for two satellites

**Comment by frolovsa** [comment]
an example of metadata for intervals

era5, cris, {[01-01-2006 10-01-2008],[01-01-2010 01-01-2999]}
mera21c, cris, {[01-01-2006 01-01-2999]}

**Comment by slawrence87544** [comment]
Here's an example yaml format (see the cris section).
plot_groupings:
- grouping_name: Hyperspectral Infrared
  data_type_families:
  - data_type_family_name: cris
    external_obs_intervals:
    - obs_src: era5
      intervals:
      - 
        start: 01-01-1999
        end: 02-15-2004
      -
        start: 09-02-2006
        end: 02-01-2009
    - obs_src: mera21c
      intervals:
      -
        start: 12-30-1998
        end: 01-01-2005
    family_members:
    - data_type: cris
      suffix: ".tm00.bufr_d"
    - data_type: crisf4
      suffix: ".tm00.bufr_d"
    - data_type: crisdb
      suffix: ".tm00.bufr_d"
  - data_type_family_name: iasi
    family_members:
    - data_type: iasidb
      suffix: ".tm00.bufr_d"
    - data_type: esiasi
      suffix: ".tm00.bufr_d"
    - data_type: mtiasi
      suffix: ".tm00.bufr_d"
  - data_type_family_name: airs
    family_members:
    - data_type: airs
      suffix: ".tm00.bufr_d"
    - data_type: airsev
      suffix: ".tm00.bufr_d"
    - data_type: airswm
      suffix: ".tm00.bufr_d"

**Comment by frolovsa** [comment]
@slawrence87544 here are the tabulated intervals
https://docs.google.com/spreadsheets/d/15r8diBtGx8pQEEM_czSCy_zluA278M3eVILNpZnDUUU/edit?pli=1#gid=1131692916
