### ISSUE TITLE
parse satinfo and convinfo files into a database

### ISSUE THREAD

**Issue by frolovsa** [noaa-psd/observation-inventory-utils#18]
We need to visualize the content of satinfo and convinfo files in the context of our observational holdings. 
satinfo and convinfo are generated on the fly using this database
/scratch2/BMC/gsienkf/Henry.Winterbottom/UFS-RNR.develop/fix/database 

We need to design a tool that will either use the existing database or will replace the existing database.

**Comment by frolovsa** [comment]
for description of the info files see:
https://dtcenter.org/sites/default/files/community-code/gsi/docs/users-guide/GSIUserGuide_v3.5.pdf (section 3)

**Comment by frolovsa** [comment]
@slawrence87544 Can we collaborate on this ticket? I will write a prototype code in matlab (should be pretty small) and you find a way to port it to your python package?

**Comment by slawrence87544** [comment]
Sure, that would be great!

**Comment by slawrence87544** [comment]
@frolovsa, however, I will say this.  There is a good chance any parsing code developed in matlab will need to be rewritten a significant amount.  Do you think you might be interested in writing a super simple python script to do the same.  It might be just the right size for a dipping of the toe into the python waters.  They are pretty warm as far as I have experienced.  I could help setup a simple single file and virtualenv if that would make things easier.
